name: mdyn
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - scipy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - statsmodels
  - shapely
  - pyproj
  - geopandas
  - pyogrio
  - fiona
  - proj
  - gdal
  - folium
  - basemap
  - basemap-data
  - basemap-data-hires
  - requests
  - tqdm
  - psutil
  - pip
  - pip:
    - windrose

